# Generated by Django 4.2.5 on 2023-09-30 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место выполения привычки')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('sign_pleasant_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('related_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Связанная привычка')),
                ('period', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='периодичность в днях')),
                ('award', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.PositiveSmallIntegerField(blank=True, default=60, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='время на выполнение')),
                ('is_published', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
